### ISSUE TITLE
Version of the Matterport3D Simulator

### ISSUE THREAD

**Issue by hekj** [YicongHong/Recurrent-VLN-BERT#1]
Hi, Yicong

When I try to config the environment of Recurrent-VLN-BERT, I find only the old version of Mattorport3D Simulator supports this code. Because the new version has changed its api like 'sim.makeAction' for Parallel navigation.  Maybe you can note this matter needing attention in readme.txt.

**Comment by YicongHong** [comment]
Hi Keji,
Thanks for pointing this out! Yes, I was using the old version of MP3D Sim, I will talk about this in README.
Meanwhile, it shouldn't be hard to change to the new version 😃 
Cheers

**Comment by hekj** [comment]
Hi, Yicong

Thank you for your attention. And for your suggestion, I'll try that. 😃
