### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.pytorch_transformers'

### ISSUE THREAD

**Issue by Jaluco** [YicongHong/Recurrent-VLN-BERT#11]
Hello, I was trying to run the model with `bash run/test_agent.bash` as instructed in your readme but i get the error:
`Optimizer: Using AdamW
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
Traceback (most recent call last):
  File "r2r_src/train.py", line 13, in <module>
    from agent import Seq2SeqAgent
  File "/Recurrent-VLN-BERT/r2r_src/agent.py", line 21, in <module>
    import model_OSCAR, model_PREVALENT
  File "/Recurrent-VLN-BERT/r2r_src/model_OSCAR.py", line 7, in <module>
    from vlnbert.vlnbert_init import get_vlnbert_models
  File "/Recurrent-VLN-BERT/r2r_src/vlnbert/vlnbert_init.py", line 3, in <module>
    from transformers.pytorch_transformers import (BertConfig, BertTokenizer)
ModuleNotFoundError: No module named 'transformers.pytorch_transformers'
`
I have transformers and pytorch transformers installed also the old version of pytorch-pretrained-bert and am unsure of what is causing this, any help? thanks in advance

**Comment by YicongHong** [comment]
Hi, it seems that the script hasn't find the installed modules. You can try to explicity adding the path to transformers to your sys path in vlnbert_init.py

**Comment by Jaluco** [comment]
Thank you very much, I'll try that asap

**Comment by Jaluco** [comment]
Sorry I didn't come back, the problem was that transformers uses the following to import those classes:
`from transformers import BertConfig, BertTokenizer`
