### ISSUE TITLE
Why don't you use ‘speaker’ during training?

### ISSUE THREAD

**Issue by CrystalSixone** [YicongHong/Recurrent-VLN-BERT#12]
Hi! I don't see any codes about 'speaker', a useful way to make data augmentation for R2R. I am wondering why you delete the speaker part in your codes? Or have you done the experiments to show that using speaker doesn't work well in your method? 
Thanks a lot!

**Comment by YicongHong** [comment]
Hi There! We apply the PREVALENT augmented data in training which is produced by a Speaker model. We didn't apply the Speaker on the fly because we believe that using the pre-processed augmented datashould be similar to sample new data with a Speaker and greatly reduces training cost.

**Comment by CrystalSixone** [comment]
Oh, I see! Thanks for your kind reply 👍
