### ISSUE TITLE
Details about the no init. OSCAR model

### ISSUE THREAD

**Issue by Jackie-Chou** [YicongHong/Recurrent-VLN-BERT#13]
Hi Yicong, I wonder how do you initialize the no init. OSCAR model to get the results reported in the paper. Did you initialize all the parameters randomly or use some pretrained weights, e.g., initialize the language part with Bert pretrained weights?

**Comment by YicongHong** [comment]
Hi Jackie, the OSCAR (no init.) was initialized with all random parameters :)

**Comment by Jackie-Chou** [comment]
Thanks for your timely reply!
