### ISSUE TITLE
is it possible to have a branch for REVERIE

### ISSUE THREAD

**Issue by volkancirik** [YicongHong/Recurrent-VLN-BERT#14]
Hello,

Thanks a lot for maintaining your open-source code!

As mentioned in #9, is it possible to have models and code available for REVERIE? I would like to have a fair comparison of your approach.

**Comment by YicongHong** [comment]
Hi Volkan,

Thanks for your interest in our work! Sorry that the REVERIE branch has been continuously postponing, thanks for the reminder, I will put it on schedule. But for now, could you please send me an email about this issue? I will reply you with temporary links to download the REVERIE code and features. Cheers!
