### ISSUE TITLE
Request to download the model and code for the REVERIE branch

### ISSUE THREAD

**Issue by LiHui1116** [YicongHong/Recurrent-VLN-BERT#17]
I have reproduce this codebase. I am writing for apply to download the model and code for the REVERIE branch which I will take it as a baseline. And I have send an email to you.
 Looking forward your reply! Thanks in advance!

**Comment by YicongHong** [comment]
Hello Hui, 
Thanks for your interest in this work. I have sent out a link to you few days ago, please double-check your email. Cheers!
