### ISSUE TITLE
Mismatch between weights?

### ISSUE THREAD

**Issue by aleSuglia** [YicongHong/Recurrent-VLN-BERT#2]
Hi there,

Congratulations for your CVPR paper and for releasing your code. I was wondering whether you could clarify the structure of the checkpoints you released. I'm interested in the OSCAR version of your model and I tried to load it. However, it looks like the following parameters cannot be found:
```
'img_projection.weight', 'img_projection.bias'
```
I tried to inspect the `VLNBert` class in the file `vlnbert_OSCAR.py` and it looks like there is not a module called `img_projection`. Instead, seems there is one in the `vlnbert_PREVALENT.py` file. In addition, even in the original OSCAR codebase I cannot find a mention to the `img_projection` layer (https://github.com/microsoft/Oscar/blob/master/oscar/modeling/modeling_bert.py). Could you please verify that the released model checkpoints are correct and referring to the correct models? 

Thanks,
Alessandro

**Comment by YicongHong** [comment]
Hi Alessandro,

Thanks! I double-checked the code, it works fine from my side. For the OSCAR-based model, `img_projection` module is defined in `model_OSCAR.py` not `vlnbert_OSCAR.py`, sorry about this inconsistency to PREVANLENT-model. 

I added the `img_projection` layer especially for this task, so it won't be in the original OSCAR code.

I also checked the OSCAR weights that I uploaded, I can see `['vln_bert']['state_dict']['img_projection.weight']` exists. And you didn't mention `action_state_project` which is a parallel module to `img_projection`, so I assume the parameters aren't missing?

So I am not very sure what caused the missing parameters issue. Could you please double-check from you side and maybe share the error message here?

Cheers

**Comment by aleSuglia** [comment]
The problem is OSCAR weights I believe expect that you have a field called `img_embedding` and not `img_projection`. So I believe in your OSCAR version you're potentially throwing away the model weights?

**Comment by YicongHong** [comment]
Yes, that's right. Some of the original OSCAR weights are not used.
