### ISSUE TITLE
R2R Test Unseen

### ISSUE THREAD

**Issue by jasscia18** [YicongHong/Recurrent-VLN-BERT#21]
Thank you so much for the great work you do. I reproduced Recurrent VLN on the R2R datasets according to the file readme.md.
But I only get the results for the validation set, how can I get the results of the Test Unseen?

**Comment by YicongHong** [comment]
Hi @jasscia18, thanks for your interest in our work! The Test Unseen ground truths are reserved on R2R's test server for fair comparison, you need to upload the result .json file to the server to see the SR/SPL/etc. (please see https://eval.ai/web/challenges/challenge-page/97/evaluation).

To get the result .json file, I believe you only need to run the `test_agent.bash` and set `--submit 1`.

Cheers,
Yicong

**Comment by jasscia18** [comment]
Hi  Yicong, I followed your instructions to run the `test_agent.   bash` script with the `--submit 1` flag to obtain the result .json.    However, I encountered an error during the execution of the script.

<img width="800" alt="1697095273034" src="https://github.com/YicongHong/Recurrent-VLN-BERT/assets/43958686/74562509-ae89-421a-86d1-aaa685418462">

I would greatly appreciate your guidance on how to address this error and successfully generate the result .json file. Any assistance  you can provide would be extremely helpful in our research efforts.

Thank you in advance for your time and support.

**Comment by YicongHong** [comment]
Hi, since we don't have the ground-truth paths for the test set, we can't measure nDTW. You only need to comment out all lines for computing nDTW. And to save time, you can set the validation data to be only `test unseen` so that you don't need to re-eval for the other three splits every time.

Cheers

**Comment by zzxrepository** [comment]
> Hi, since we don't have the ground-truth paths for the test set, we can't measure nDTW. You only need to comment out all lines for computing nDTW. And to save time, you can set the validation data to be only `test unseen` so that you don't need to re-eval for the other three splits every time.
> 
> Cheers

I had comment out all lines for computing nDTW,but there is still some problem：

![Image](https://github.com/user-attachments/assets/c5f0dbf0-61a7-4497-a838-610bf1ae38f0)   

![Image](https://github.com/user-attachments/assets/2dc802a8-fa5b-4c43-96b7-c16397820c78)

![Image](https://github.com/user-attachments/assets/fc67759a-520d-456f-badb-e2cb321a889e)
