### ISSUE TITLE
can you give me an Augmented data download link

### ISSUE THREAD

**Issue by LeeGe91** [YicongHong/Recurrent-VLN-BERT#24]
I cannot download Augmented data

**Comment by YicongHong** [comment]
Could you specify the error? The [link](https://zenodo.org/record/4437864/files/prevalent_aug.json?download=1) works very well on my side.

**Comment by LeeGe91** [comment]
i'm sorry,but i really can't download it,can you send it yo my onedrive online disk? thanks
