### ISSUE TITLE
How to download panoramic images？

### ISSUE THREAD

**Issue by lizixiaoboluo** [YicongHong/Recurrent-VLN-BERT#25]
Thank you very much for your excellent work! 

Could you please share how to download panoramic images and obtain visualizations for navigation?

 I really appreciate your help!

**Comment by YicongHong** [comment]
Hi there, Thanks! 

Please refer to Peter's [Matterport3D Simulator](https://github.com/peteanderson80/Matterport3DSimulator) for getting the panoramic images. Cheers!
