### ISSUE TITLE
Specify license for the code

### ISSUE THREAD

**Issue by aleSuglia** [YicongHong/Recurrent-VLN-BERT#3]
Hello,

Thanks again for your codebase. It was very useful indeed and congratulations for your accepted paper. I was wondering whether you could please add a license to your codebase so that it's very clear how this code can be used by third parties.

Thanks,
Alessandro

**Comment by YicongHong** [comment]
Hi Alessandro,

Thank you very much for asking, I have added a MIT license for the code. 😃

Cheers,
Yicong

**Comment by aleSuglia** [comment]
That's great. Thanks again!
